FROM apache/airflow:2.3.0
USER airflow
RUN pip install --no-cache-dir pymongo==3.6.0
RUN pip install --no-cache-dir dnspython==1.13.0
RUN pip install --no-cache-dir apache-airflow-providers-mongo==2.3.3